name: CombatLog
version: 1.1.0
main: jre.frwostella.combatLogPlugin.CombatLogPlugin
api-version: 1.21.11
author: Frwostella
contributors: [ Shotadft ]
website: https://github.com/Frwostella/CombatLogPlugin

commands:
  combatlog:
    description: CombatLog main command
    usage: /combatlog reload

permissions:
  combatlog.reload:
    default: op